######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 11 00:09:08 2009
######################################################################

TEMPLATE = app
TARGET = martex
DEPENDPATH += .
INCLUDEPATH += .

SOURCES += main.cpp

include (../globinclude.pri)

TRANSLATIONS = $$GLOBTRANS
RESOURCES   += $$GLOBRESOURCES



