# #####################################################################
# Automatically generated by qmake (2.01a) ?? ???. 11 09:42:50 2009
# #####################################################################
TEMPLATE = lib
TARGET = QtLoad
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += lib.cpp \
    filter.cpp
HEADERS += filter.h
