######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 11 00:09:08 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h main.cpp
SOURCES += main.cpp widget.cpp
