#ifndef REQUESTTOREMOTE_H
#define REQUESTTOREMOTE_H

#include <QString>

#define DEFINE_COMMAND( CMD ) const QString CMD = #CMD;


DEFINE_COMMAND( SPY_START_0 );
DEFINE_COMMAND( SPY_STOP_0 );

DEFINE_COMMAND( RECORDING_START_1 );
DEFINE_COMMAND( RECORDING_STOP_1 );
DEFINE_COMMAND( RECORDING_GET_1 );
DEFINE_COMMAND( RECORDING_OUTPUT_1 );

DEFINE_COMMAND( PLAYBACK_UPLOAD_2 );
DEFINE_COMMAND( PLAYBACK_PLAY_1 );
DEFINE_COMMAND( PLAYBACK_STOP_0 );
DEFINE_COMMAND( PLAYBACK_FINISHED_0 );
DEFINE_COMMAND( PLAYBACK_TEST_START_1 );
DEFINE_COMMAND( PLAYBACK_TEST_DONE_2 );



#endif // REQUESTTOREMOTE_H
