#ifndef REQUESTTOREMOTE_H
#define REQUESTTOREMOTE_H

#include <QString>

#define DEFINE_COMMAND( CMD ) const QString CMD = "CMD";


DEFINE_COMMAND( SPY_START );
DEFINE_COMMAND( SPY_STOP );

DEFINE_COMMAND( RECORDING_START );
DEFINE_COMMAND( RECORDING_STOP );
DEFINE_COMMAND( RECORDING_GET );

DEFINE_COMMAND( PLAYBACK_UPLOAD );
DEFINE_COMMAND( PLAYBACK_PLAY );
DEFINE_COMMAND( PLAYBACK_STOP );



#endif // REQUESTTOREMOTE_H
